site_name: LSP Mode
nav:
  - Home: /
  - LSPs:
      - Dart: https://emacs-lsp.github.io/lsp-dart
      - Docker: https://github.com/emacs-lsp/lsp-docker
      - Haskell: https://github.com/emacs-lsp/lsp-haskell
      - Java: https://emacs-lsp.github.io/lsp-java
      - MSSQL: https://github.com/emacs-lsp/lsp-mssql
      - Python MS: https://github.com/emacs-lsp/lsp-python-ms
  - UI: https://github.com/emacs-lsp/lsp-ui
  - Debugging: https://github.com/emacs-lsp/dap-mode
  - Integrations:
      Treemacs: https://github.com/emacs-lsp/lsp-treemacs
      Helm: https://github.com/emacs-lsp/helm-lsp
      Ivy: https://github.com/emacs-lsp/lsp-ivy
  - Changelog: /CHANGELOG

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/expanded_nav.js

theme:
  name: material
  logo: examples/logo-mini.png
  favicon: examples/logo-mini.png
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emacs-lsp/lsp-mode
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yonchovski
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/emacs-lsp/lsp-mode

repo_name: emacs-lsp/lsp-mode
repo_url: https://github.com/emacs-lsp/lsp-mode

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: '#'

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
